extends:
  - "plugin:react/recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"

plugins:
  - "react"
  - "react-hooks"
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 8

env:
  es6: true
  browser: true
  jest: true
  node: true

settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions: [.js, .jsx, .ts, .tsx]

rules:
  prefer-const: 0
  no-console: 0
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  react/display-name: off
  react/prop-types: off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/array-type": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-object-literal-type-assertion": off
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/prefer-interface": off
  "@typescript-eslint/no-unused-vars":
    - error
    -
      vars: all
      args: after-used
      ignoreRestSiblings: true
      varsIgnorePattern: ^_
