extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
  - "plugin:react/recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "react-hooks"
rules:
  "@typescript-eslint/prefer-interface": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/no-use-before-define": "off"
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"
  "no-console": "off"
  "indent":
    - error
    - 2
